Css in js
BagrovAnatoli/skypro-music pull request #3
Opened 2022-08-16 13:45 UTC by BagrovAnatoli

Переписал проект, применив подход css-in-js

2022-08-17 06:41 UTC, mrerberg commented
У тебя выбрана не самая лучшая структура проекта. Ты можешь писать с помощью компонентного подхода, при этом, у тебя все стили в одном файле. Это ошибка. Удобнее всего создавать под каждый компонент папку (components/Button, components/Track) и в этой папке хранить все файлы, нужные компоненту.

index.jsx - файл с компонентом
styles.js - стили данного компонента

2022-08-17 06:41 UTC, mrerberg requested changes

2022-08-17 06:41 UTC, mrerberg commented on src/App.jsx
> +            <footer/>
Это можно удалить

2022-08-17 06:41 UTC, mrerberg commented on src/CenterBlock.jsx
> +            <S.CenterBlockH2>Треки</S.CenterBlockH2>
Не привязывайся в названиях компонента к конкретному тегу. Поменяется тег - поменяется и компонент, не хорошо

2022-08-17 06:41 UTC, mrerberg commented on src/Contain.jsx
> +                <S.TrackPlaySvg alt="music">
Сайт на русском, может и alt на русском?

2022-08-17 06:41 UTC, mrerberg commented on src/Contain.jsx
> +                <S.TrackPlayAuthorLink href="http://">Ты та...</S.TrackPlayAuthorLink>
Мне кажется, можно в разы сократить названия компонентов, убрав префикс Track. Я бы Track задал названию общего компонента

2022-08-17 06:41 UTC, mrerberg commented on src/Contain.jsx
>          isLoading ? <IsLoadingContain /> :
Проще назвать такой компонент Skeleton. Все ясно и понятно, глагол не используют в названии компонента (is)

2022-08-17 06:41 UTC, mrerberg commented on src/Controls.jsx
> +            {controlBtnsValues.map(({name, alt, xlinkHref, cursor, hoverIcon}) => (
Тянет на отдельный компонент, в который будут прокидываться данные пропсы

```js
=> (
  <SomeComponent name={,,,} alt={...} />
)
```

2022-08-17 06:41 UTC, mrerberg commented on src/Filter.jsx
> +            <S.CenterBlockFilter onClick={handleFilterClick} aria-hidden="true">
CenterBlock очень...абстрактное и при этот слишком точное название. Может просто TracksFilters? Filters?

2022-08-17 06:41 UTC, mrerberg commented on src/FilterPopup.jsx
>      switch ( filterBy ) {
Каждый такой фильтр нужно реализовать отдельно, не нужно делать через условия. Когда добавится логика, будет сложно поддерживать такой компонент

2022-08-17 06:41 UTC, mrerberg commented on src/PlaylistItem.jsx
>      const loadingTrack = (
Можно вынести в отдельный компонент TrackSlkeleton

2022-08-17 06:41 UTC, mrerberg commented on src/index.js
> +// import './App.css';
Мертвый код

2022-08-17 06:42 UTC, mrerberg requested changes

2022-08-17 06:42 UTC, mrerberg commented on src/styles.js
> +export const MainNav = styled.div`
По ощущениям, у тебя диватоз.

https://www.youtube.com/watch?v=mAoxm-AyNCw

2022-08-17 07:19 UTC, BagrovAnatoli commented on src/Filter.jsx
> +            <S.CenterBlockFilter onClick={handleFilterClick} aria-hidden="true">
Я бы с радостью всё посокращал. Но это же стилевые компоненты, которые находятся в конкретном месте на экране. Мне кажется, что поэтому лучше точнее указывать, название, чтобы понимать, где это находится.

2022-08-25 07:40 UTC, mrerberg commented on src/Filter.jsx
> +            <S.CenterBlockFilter onClick={handleFilterClick} aria-hidden="true">
Нет, дотошное описание необязательно, оно не всегда несет полезное нагрузку

2022-08-25 07:43 UTC, mrerberg requested changes

2022-08-25 07:43 UTC, mrerberg commented on src/App.jsx
> +            <footer/>
Зачем тебе футер? Его можно удалить

2022-08-25 07:43 UTC, mrerberg commented on src/Bar.jsx
> +            <S.BarPlayerProgress />
Зачем тебе приставки Bar? И так ясно, что ты стилизуешь компоненты в Bar.jsx

2022-08-25 07:43 UTC, mrerberg commented on src/CenterBlock.jsx
> +            <S.CenterBlockH2>Треки</S.CenterBlockH2>
Не привязывайся в названиях компонента к конкретному тегу. Поменяется тег - поменяется и компонент, не хорошо

2022-08-25 10:45 UTC, BagrovAnatoli commented on src/App.jsx
> +            <footer/>
Удалил.

2022-08-25 10:46 UTC, BagrovAnatoli commented on src/Bar.jsx
> +            <S.BarPlayerProgress />
Когда пеходил со стилизации с помощью классов на class-component я переименовывал так, чтобы не запутаться.

2022-08-25 18:32 UTC, BagrovAnatoli commented on src/App.jsx
> +            <footer/>
footer имеешь ввиду? удалил.

2022-08-25 18:34 UTC, BagrovAnatoli commented on src/CenterBlock.jsx
> +            <S.CenterBlockH2>Треки</S.CenterBlockH2>
Принял.
https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/7f53a2ce2a7d5d8f1220dfa96d8db30e5d78e116

2022-08-25 18:34 UTC, BagrovAnatoli commented on src/Contain.jsx
> +                <S.TrackPlaySvg alt="music">
В том-же коммите перевёл на русский https://github.com/BagrovAnatoli/skypro-music/pull/3#discussion_r955295909

2022-08-25 18:37 UTC, BagrovAnatoli commented on src/Contain.jsx
> +                <S.TrackPlayAuthorLink href="http://">Ты та...</S.TrackPlayAuthorLink>
По ходу коммитов, было несколько последовательных переименований, в основном в последних двух:
https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/8f1c869574e8f9ee8fd9c55622c4bbd9c6ac70d4
https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/3649ef6c5fc5e3873a799638ec03aafcbe096e4a

2022-08-25 18:37 UTC, BagrovAnatoli commented on src/Contain.jsx
>          isLoading ? <IsLoadingContain /> :
https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/cdb640432788c4df9c58abf3c380088960c1ef60
и
https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/4723b1378475de8f7604a5ea1e2a5f8344f71e52

2022-08-25 18:40 UTC, BagrovAnatoli commented on src/Filter.jsx
> +            <S.CenterBlockFilter onClick={handleFilterClick} aria-hidden="true">
Сократил.

2022-08-25 18:41 UTC, BagrovAnatoli commented on src/FilterPopup.jsx
>      switch ( filterBy ) {
О, это было самое непонятное. И даже несмотря на то, что теперь тоже работает, не до конца разобрался в том, как именно. 
https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/849ae5e7b45547736dd5302c9e35ef25b9f4355b

2022-08-25 18:43 UTC, BagrovAnatoli commented on src/PlaylistItem.jsx
>      const loadingTrack = (
В комментарии в https://github.com/BagrovAnatoli/skypro-music/pull/3#discussion_r955299004 вторая ссылка такая-же:
https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/4723b1378475de8f7604a5ea1e2a5f8344f71e52

2022-08-25 18:43 UTC, BagrovAnatoli commented on src/index.js
> +// import './App.css';
Убрал.

2022-08-25 18:47 UTC, BagrovAnatoli commented on src/styles.js
> +export const MainNav = styled.div`
Ну, наверно, это естественно. Вёрстку макета нам дали готовую. И Диватоз от верстальщика передался мне. Заразная штука) Да и на курсе не рассказывалось, что есть такая болезнь и как от неё лечиться.

Ещё, если что-то искать на форумах, то там часто предлагают оборачивать элементы в обёртки. И даже функции оборачивать в другие функции. В общем, похоже, что у нас эпидемия диватоза)

Если есть что почитать, о приёмах борьбы с ним, буду благодарен. Если что-то у тебя на примете есть такое.

2022-08-25 18:49 UTC, BagrovAnatoli commented on src/Bar.jsx
> +            <S.BarPlayerProgress />
Есть. Вот тут соответствующие коммиты https://github.com/BagrovAnatoli/skypro-music/pull/3#discussion_r955298522

2022-08-28 09:16 UTC, mrerberg commented on src/App.jsx
> +            <footer/>
Да, я прикрепил коммент к строке, где футер

2022-08-28 09:24 UTC, mrerberg requested changes

2022-08-28 09:24 UTC, mrerberg commented on src/components/Bar/styles.js
> +    -webkit-box-direction: normal;
Стили с префиксами можно удалить, их проставит styled-components

2022-08-28 09:24 UTC, mrerberg commented on src/components/CenterBlock/styles.js
> +export const Head = styled.h2`
А не h1? Это не самый ли главный заголовок?

2022-08-28 09:24 UTC, mrerberg commented on src/components/Controls/styles.js
> +            width: 15px;
Данный стили (размеры) проще задать через props, если есть такая возможность

2022-08-28 09:24 UTC, mrerberg commented on src/components/Controls/styles.js
> +            fill: #D9D9D9;
Почему и иконок одинаковых разные цвета?

2022-08-28 09:24 UTC, mrerberg commented on src/components/Controls/styles.js
> +        &:hover svg{
пробел после svg

svg {}

2022-08-28 09:24 UTC, mrerberg commented on src/components/Filter/index.jsx
> +
Форматирование не работает? Почему так много лишних пустых строк?

2022-08-28 09:24 UTC, mrerberg commented on src/components/Filter/styles.js
> +export const ButtonTextActiveMixin = css`
Ты используешь еще где-то данный миксин? Я бы ее сделал функцией

2022-08-28 09:24 UTC, mrerberg commented on src/components/FilterPopup/index.jsx
> +    switch ( filterBy ) {
На каждый фильтр - отдельный попап. Не нужно городить подобные конструкции, они не расширяемы

2022-08-28 09:24 UTC, mrerberg commented on src/components/Filters/index.jsx
> +/* eslint-disable no-console */
Забыл удалить

2022-08-28 09:24 UTC, mrerberg commented on src/components/Filters/index.jsx
> +
Запусти по всем файлам преттиер

2022-08-28 17:23 UTC, BagrovAnatoli commented on src/components/Controls/styles.js
> +            fill: #D9D9D9;
Так в макете: https://www.figma.com/community/file/1140990237442148320
Не знаю, какая задумка у дизайнера: чтобы три основные кнопки были более яркими, чем две правые или чтобы все одинаковые, а разными цветами показана разница между активной кнопкой и обычной.
На данный момент к этим кнопкам я не делал стили с эффектом наведения и нажатия.

2022-08-28 17:32 UTC, BagrovAnatoli commented on src/components/Filter/styles.js
> +export const ButtonTextActiveMixin = css`
Нет, только в этом файле, но в двух местах.
А почему ты бы функцией сделал? Как константа эти стили занимают минимум места. Остаётся просто вставить, в нужное место. А если делать функцией, то надо будет после неё скобки ставить.

2022-08-28 17:53 UTC, BagrovAnatoli commented on src/components/FilterPopup/index.jsx
> +    switch ( filterBy ) {
Не совсем понял. Ты предлагаешь сделать вместо одного компонента три? Чтобы если вдруг появится новый фильтр, то создавать новый компонент?
У меня ещё данные в отдельных файлах для каждого фильтра. Так сделал пока мы не получаем их по API. Потом всё равно придётся переделывать. А если пока так, в отдельных файлах, то вот этакую строку 
`content = authorsData.map((author) => <S.Text key={author.id}>{author.author}</S.Text>);`
генерировать внутри map не знаю, как. Может с помощью eval, но это как-то не очень.
`eval(filterName + 'Data.map((' + filterName  + ') => <S.Text key={' + filterName  + '.id}>{' + filterName  + '.' + filterName  + '}</S.Text>'));`

Другие решения, по-моему, возможны только если пересмотреть в целом реализацию фильтра. Когда через API бедм получать данные, перепишу иначе.

2022-08-28 17:55 UTC, BagrovAnatoli commented on src/components/Filters/index.jsx
> +/* eslint-disable no-console */
Убрал

2022-08-29 15:03 UTC, BagrovAnatoli commented on src/components/Bar/styles.js
> +    -webkit-box-direction: normal;
Почистил стили
https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/bace086d38380cc84c088f1e9a847ad001a25bf6

2022-08-29 15:07 UTC, BagrovAnatoli commented on src/components/CenterBlock/styles.js
> +export const Head = styled.h2`
Наверно. Заменил тег https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/6dc8cdd1344b92ba52f8515b624ffaa3dde054ea

2022-08-29 15:09 UTC, BagrovAnatoli commented on src/components/Controls/styles.js
> +            width: 15px;
Вынес размеры в constants.js и передаю в props.
https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/4063f5f02a5989b6a8143fa32579649cc4aee6d7

2022-08-29 15:10 UTC, BagrovAnatoli commented on src/components/Controls/styles.js
> +        &:hover svg{
Убрал. Позже прогнал prettier по всем файлам

2022-08-29 15:11 UTC, BagrovAnatoli commented on src/components/Filter/index.jsx
> +
Наверно, настройки по-умолчанию в CRA  не включают автоматическое форматирование.

2022-08-29 15:12 UTC, BagrovAnatoli commented on src/components/Filters/index.jsx
> +
Запустил.
https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/d916beeeb84c983f6d11456482688f58691b1f6b

2022-08-30 06:00 UTC, mrerberg commented on src/styles.js
> +export const MainNav = styled.div`
Тут проще изучить какие вообще существуют теги и для чего применяются. К сожалению, у меня нет под рукой какой-нибудь отличной статьи или видоса. Я лишь рекомендую смотреть, можно ли заменить div на более семантичный тег

2022-08-30 06:00 UTC, mrerberg commented on src/components/Controls/styles.js
> +            fill: #D9D9D9;
Да, все логично, спасибо

2022-08-30 06:02 UTC, mrerberg commented on src/components/Filter/styles.js
> +export const ButtonTextActiveMixin = css`
Если этот миксин нигде не используется, то тогда не надо его экспортировать.

Во-первых, миксин стоит назвать с маленькой буквы, так как это не компонент. Про функцию. **Чисто** **предпочтение**. Оно ассоциируется с  js функциями миксинами. Это общий паттерн в программировании.

2022-08-30 06:04 UTC, mrerberg commented on src/components/FilterPopup/index.jsx
> +    switch ( filterBy ) {
Вообще, именно компонент фильтра можно сделать универсальным, лишь передавая в него контент

<Filter items={...} {...} />

А где-то в родителе уже получать элементы, писать логику выбора и так далее

2022-08-30 06:19 UTC, mrerberg requested changes

2022-08-30 06:19 UTC, mrerberg commented on src/components/CenterBlock/index.jsx
> +      <S.Head>Треки</S.Head>
Кстати, это тянет на отдельный компонент заголовка, так как повторяется по стилям на других страницах

2022-08-30 06:19 UTC, mrerberg commented on src/components/Filter/styles.js
> +  border-color: #ad61ff;
Кстати, можно пользоваться переменными. Есть смысл занести основные цвета в переменные. Либо в виде js переменных, либо css var(--someVar)

2022-08-30 06:19 UTC, mrerberg commented on src/components/LikeDislike/styles.js
> +  width: 14.34px;
Округли)

2022-08-30 06:19 UTC, mrerberg commented on src/components/LikeDislike/styles.js
> +  margin-left: 28.5px;
Округли

2022-08-30 06:19 UTC, mrerberg commented on src/components/Logo/index.jsx
> +    <S.NavLogo>
Это вполне можно сделать ссылкой на главную страницу

2022-08-30 06:19 UTC, mrerberg commented on src/components/Logo/styles.js
> +  width: 113.33px;
Округли

2022-08-30 06:19 UTC, mrerberg commented on src/components/Nav/styles.js
> +export default MainNav;
Зачем тебе дефолтный экспорт, если ты и так экспортируешь компонент на 3 строке?

2022-08-30 06:19 UTC, mrerberg commented on src/components/Personal/index.jsx
> +  if (!isLoading) {
Обычно, сначала обрабатывают негативный сценарий в начале. В твоем случае

```
if(isLoading) {
  return null;
}


  return (
      <S.SidebarPersonal>
        <S.SidebarPersonalName>{props.name}</S.SidebarPersonalName>
        <S.SidebarAvatar />
      </S.SidebarPersonal>
    );

```

2022-08-30 06:19 UTC, mrerberg commented on src/components/Personal/index.jsx
> +  if (!isLoading) {
Так проще понять и этот вариант гораздо понятнее

2022-08-30 06:19 UTC, mrerberg commented on src/components/Personal/index.jsx
>  function Personal(props) {
Рекомендую деструкторизировать пропсы

2022-08-30 06:19 UTC, mrerberg commented on src/components/PlaylistTitle/index.jsx
> +      <S.PlaylistTitleCol $col="2">ИСПОЛНИТЕЛЬ</S.PlaylistTitleCol>
Капслок задай стилем в css

2022-08-30 06:19 UTC, mrerberg commented on src/components/PlaylistTitle/styles.js
> +  ${(props) => props.$col === '4' && `text-align: end;`}
А не проще через :last-of-type?

2022-08-30 06:19 UTC, mrerberg commented on src/components/Search/index.jsx
> +      <S.SearchText type="search" placeholder="Поиск" name="search" />
У текста не может быть type="search", а у input может быть

2022-08-30 06:19 UTC, mrerberg commented on src/components/Sidebar/index.jsx
> +    <S.SidebarItem $isLoading key={item} />
Обычно скелетоны делают [отдельным компонентом](https://core-ds.github.io/core-components/master/?path=/docs/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-skeleton--skeleton), чтобы не приходилось передавать специальный проп

<S.SidebarItem $isLoading />

2022-08-30 06:19 UTC, mrerberg commented on src/components/TrackTitle/index.jsx
> +  const textTitle = text || '';
Можно задать дефолтные значения при деструкторизации свойст объекта

2022-08-30 06:19 UTC, mrerberg commented on src/components/TrackTitle/styles.js
> +export const { Title } = S;
export const { Title, TitleImage  } = S;

2022-08-30 06:19 UTC, mrerberg commented on src/components/TrackTitle/styles.js
> +export const { Title } = S;
А зачем тебе реэкспорт?

2022-08-30 06:19 UTC, mrerberg commented on src/constants.js
> +export const ICON_NOTE = 'img/icon/sprite.svg#icon-note';
Я бы рекомендовал делать не через спрайт, а вставлять начинку иконки в отдельный компонент иконки. Это потом хорошо оптимизируется

2022-08-30 08:55 UTC, BagrovAnatoli commented on src/components/TrackTitle/styles.js
> +export const { Title } = S;
Вот смотри, есть папка First, в ней файлы index.jsx и styles.js
Есть папка Second, в ней файлы index.jsx и styles.js

Чтобы в Second/index.js импортировать стили не из разных файлов, а из одного, я туда импортирую Second/styles.js, а уже в него импортирую стиль из First/styles.js

То есть, я не хочу импортировать стили двумя строчками из разных мест. Но ещё больше я не хочу, импортировать  Second/styles.js как S, а First/styles.js как Styles, чтобы все styled-components имели одинаковый префикс S.

И не хочу дублировать одинаковые стили в разных компонентах, поэтому использую импорт из одного в другой.

2022-08-30 09:15 UTC, BagrovAnatoli commented on src/Controls.jsx
> +            {controlBtnsValues.map(({name, alt, xlinkHref, cursor, hoverIcon}) => (
Так он уже есть:
```
<PlayerBtn
          name={name}
          alt={alt}
          xlinkHref={xlinkHref}
          width={CONTROLS_SIZES[name].width}
          heght={CONTROLS_SIZES[name].height}
          cursor={cursor}
          hoverIcon={hoverIcon}
          key={name}
        />
```
А controlBtnsValues - это массив, он ничего не возвращает. Ты предлагаешь просто инициализацию массива вынести в другой компонент? Но это же не компонент, ведь он ничего не рендерит. Максимум - в константы можно перенести.

2022-08-30 10:52 UTC, BagrovAnatoli commented on src/components/Filter/styles.js
> +  border-color: #ad61ff;
В styled components применимо css var(--someVar)?

2022-09-01 10:54 UTC, BagrovAnatoli commented on src/components/Nav/styles.js
> +export default MainNav;
Eslint настроен так, чтобы предпочтение отдавалось экспорту по-умолчанию, если экспортируется единственный объект
"Prefer default export"
А почему я не убираю экспорт с третьей строки при этом, так это для того, чтобы в index.jsx обратиться к стилевой компоненте по имени через точку.

2022-09-01 10:56 UTC, BagrovAnatoli commented on src/components/Nav/styles.js
> +export default MainNav;
![Экспорт по умолчанию](https://user-images.githubusercontent.com/35974249/187897911-21e14a96-0c9d-471e-8e8e-006d4e3d307e.PNG)
![Обычный экспорт](https://user-images.githubusercontent.com/35974249/187897942-24d0fd0e-d426-4b68-a6ad-57446615b26f.PNG)

2022-09-01 11:19 UTC, BagrovAnatoli commented on src/components/PlaylistTitle/index.jsx
> +      <S.PlaylistTitleCol $col="2">ИСПОЛНИТЕЛЬ</S.PlaylistTitleCol>
В стилях он уже есть. А почему тут по-разному написано, не помню. Наверно, трек я сам написал, а остальные скопировал.

2022-09-01 11:49 UTC, BagrovAnatoli commented on src/components/PlaylistTitle/styles.js
> +  ${(props) => props.$col === '4' && `text-align: end;`}
Нас учили не привязываться к отношениям типа родитель - ребёнок, потому что если кто-то решит обернуть каждого ребёнка в новый тег, то это сломается.
Но я действительно забыл, что есть такой псевдокласс, спасибо.

2022-09-01 11:55 UTC, BagrovAnatoli commented on src/components/Search/index.jsx
> +      <S.SearchText type="search" placeholder="Поиск" name="search" />
Переименовал в Input

2022-09-01 12:09 UTC, BagrovAnatoli commented on src/components/Sidebar/index.jsx
> +    <S.SidebarItem $isLoading key={item} />
Благодарю за замечание.
Но изначально у меня даже слова скелетон не было) Неужели из-за того, что я теперь употребляю слово скелетон непременно нужен отдельный компонент?
Можно я пока так оставлю? Что-то не хочется менять. Может потом.
Разве целый новый компонент  (то есть папка для него, потом два файла (index и styles)) это лучше, чем немного более универсальный уже существующий компонент?
Если делать новый компонент, то надо будет реэкспорт стилей сделать из одного в другой. Это, наверно, не очень хорошо.

2022-09-01 12:36 UTC, BagrovAnatoli commented on src/constants.js
> +export const ICON_NOTE = 'img/icon/sprite.svg#icon-note';
Пока не научился так(

2022-09-01 12:40 UTC, BagrovAnatoli commented on src/components/Filter/styles.js
> +export const ButtonTextActiveMixin = css`
Экспорт убрал.

2022-09-01 12:40 UTC, BagrovAnatoli commented on src/components/FilterPopup/index.jsx
> +    switch ( filterBy ) {
https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/d96b01ad36fc5d182ed736bd6d43afb73147e11c

2022-09-01 12:41 UTC, BagrovAnatoli commented on src/components/CenterBlock/index.jsx
> +      <S.Head>Треки</S.Head>
Вынес в отдельный компонент https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/4ee02f7ffad66ae52075a6ca56a05537b686118e

2022-09-01 12:42 UTC, BagrovAnatoli commented on src/components/Filter/styles.js
> +  border-color: #ad61ff;
Сделал как JS переменные https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/2695f76f0e47722150f25419f4dd7f4c2d952e3e

2022-09-01 12:42 UTC, BagrovAnatoli commented on src/components/LikeDislike/styles.js
> +  width: 14.34px;
Округлил вверх https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/85c756270efb2136e06f756f6da8768d508ebb93

2022-09-01 12:43 UTC, BagrovAnatoli commented on src/components/LikeDislike/styles.js
> +  margin-left: 28.5px;
В этом-же коммите https://github.com/BagrovAnatoli/skypro-music/pull/3#discussion_r960606692

2022-09-01 12:43 UTC, BagrovAnatoli commented on src/components/Logo/index.jsx
> +    <S.NavLogo>
Сделал

2022-09-01 12:43 UTC, BagrovAnatoli commented on src/components/Logo/styles.js
> +  width: 113.33px;
Округлил https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/9bbbf71691b3576b23b101fea65d25c1225cc13d

2022-09-01 12:44 UTC, BagrovAnatoli commented on src/components/Personal/index.jsx
> +  if (!isLoading) {
Поправил https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/f39543ec7559c6187ea3b38100d88cdd1e88bdd1

2022-09-01 12:45 UTC, BagrovAnatoli commented on src/components/Personal/index.jsx
>  function Personal(props) {
Есть https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/aa1ef12cc18fac42a4b459185f12af788472cc83

2022-09-01 12:46 UTC, BagrovAnatoli commented on src/components/TrackTitle/index.jsx
> +  const textTitle = text || '';
А и правда) https://github.com/BagrovAnatoli/skypro-music/pull/3/commits/23f0750b51fa6c1b5c1dde14725785550923ea01

2022-09-02 07:16 UTC, mrerberg requested changes

2022-09-02 07:16 UTC, mrerberg commented on src/colors.js
> +export const sceleton = '#313131';
skeleton

2022-09-02 07:16 UTC, mrerberg commented on src/components/Nav/styles.js
> +export default MainNav;
Можно eslint правило это отключить, оно роли не играет. Просто вносит путаницы немного

2022-09-02 20:43 UTC, merged