Routes
BagrovAnatoli/skypro-music pull request #4
Opened 2022-09-05 07:55 UTC by BagrovAnatoli

Добавил страницы логина, регистрации, плейлистов и навигацию по ним. Механизм логина и регистрации пока отсутствует. Зона зарегистрированного и незарегистрированного пользователя определяется наличием или отсутствием куки "token"

2022-09-09 05:44 UTC, mrerberg requested changes

2022-09-09 05:44 UTC, mrerberg commented on src/components/Content/index.jsx
> +/* eslint-disable no-console */
Зачем?

2022-09-09 05:44 UTC, mrerberg commented on src/components/Content/index.jsx
> +  function getTracksByPlylistId(id) {
Можно вынести функцию из компонента

2022-09-09 05:44 UTC, mrerberg commented on src/pages/login/styles.js
> +    &::-webkit-input-placeholder {
Свойства с префиксами не нужно вставлять, за тебя это сделает styled components

2022-09-09 05:44 UTC, mrerberg commented on src/pages/my-tracks/index.jsx
> +            <h1>MyTracks</h1>
На всех страницах один и тот же заголовок. Мб сделать компонент заголовка?

2022-09-09 05:44 UTC, mrerberg commented on src/pages/playlist/index.jsx
> +    const playlistId = urlId >= 0 ? urlId : Number(id);
Зачем это условие?

2022-09-09 05:44 UTC, mrerberg commented on src/styles.js
> +// export const NavMenu = styled.div`
Мертвый код

2022-09-10 15:17 UTC, BagrovAnatoli commented on src/components/Content/index.jsx
> +/* eslint-disable no-console */
Забываю подчищать. Убрал.

2022-09-10 15:37 UTC, BagrovAnatoli commented on src/components/Content/index.jsx
> +  function getTracksByPlylistId(id) {
Из коммпонента вынес. Но может ты предлагаешь вообще в другой файл вынести?

2022-09-10 16:39 UTC, BagrovAnatoli commented on src/pages/login/styles.js
> +    &::-webkit-input-placeholder {
Ясно. Это я где-то в интернете подсмотрел. Насколько помню, я пробовал написать короче, но что-то не получалось. А сейчас получилось:
```
&::placeholder {
        color: ${COLORS.grey};
    }
```

2022-09-10 16:46 UTC, BagrovAnatoli commented on src/pages/my-tracks/index.jsx
> +            <h1>MyTracks</h1>
Этот компонент оказался лишним. Удалил.

2022-09-10 17:03 UTC, BagrovAnatoli commented on src/pages/playlist/index.jsx
> +    const playlistId = urlId >= 0 ? urlId : Number(id);
Чтобы по запросу playlist/0 и my-tracks открывалось одно и тоже. В первом случае id передаётся и это 0, а во
втором id не передаётся. Без этих условий где-то аозникала ошибка обращения к undefined.
Просто структура плейлистов одинаковая и данные для my-playlist в базе данных я разместил под инжексом 0.

Я хотел сделать редирект с playlist/0 на my-tracks, но что-то не получилось.

2022-09-10 17:05 UTC, BagrovAnatoli commented on src/styles.js
> +// export const NavMenu = styled.div`
Удалил. Почему-то этот код тоже оказался ненужным.

2022-09-10 17:19 UTC, BagrovAnatoli commented on src/components/Content/index.jsx
> +/* eslint-disable no-console */
https://github.com/BagrovAnatoli/skypro-music/pull/4/commits/e340ac847f87eb363e3cb256c0b2185700d390ad
Этот коммит содержит исправления по всем следующим вопросам тоже.

2022-09-11 12:33 UTC, mrerberg commented on src/components/Content/index.jsx
> +  function getTracksByPlylistId(id) {
Можно вынести в файл (helpers, utils), который будет в папке компонента лежать, не принципиально

2022-09-11 12:35 UTC, mrerberg commented on src/pages/playlist/index.jsx
> +    const playlistId = urlId >= 0 ? urlId : Number(id);
Не забудь про это место, когда будешь получать данные с реального сервера. Это можно будет удалить. Можно TODO коммент оставить

2022-09-11 12:37 UTC, mrerberg requested changes

2022-09-11 12:37 UTC, mrerberg commented on src/components/PlaylistPage/index.jsx
> +function PlaylistPage({ playlistId }) {
Рекомендую компоненты страниц вынести в другую папку - pages

2022-09-11 12:37 UTC, mrerberg commented on src/data/menuInfo.json
> +  { "value": "Главное", "href": "/", "id": 0 },
Главная?

2022-09-13 14:53 UTC, merged